# Generated by Django 5.0 on 2023-12-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_order_customer_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(default='Customer name', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(default='Order', max_length=100),
        ),
    ]
